server:
  port: 8080
  contextPath: /v1


spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:~/simple-ticket-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: none
    
    spring:
    thymeleaf:
    cache: false
